<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find rc_description)/urdf/common/mecanum_wheel.urdf.xacro"/>
    
    <xacro:property name="wheel_track" value="0.37116"/>
    <xacro:property name="wheel_base" value="0.4164"/>
    <xacro:property name="wheel_offset_z" value="-0.02"/>

    <xacro:macro name="chassis" params="roller_type">
        <link name="dummy"> 
        </link>
        <link name="base_link">
        <inertial>
        <origin
            xyz="0.0 7.68E-18 0.0122"
            rpy="0 0 0" />
        <mass
            value="15.977" />
        <inertia
            ixx="0.04687"
            ixy="-0.00075"
            ixz="0.00335"
            iyy="0.02883"
            iyz="5.30219E-18"
            izz="0.07309" />
        </inertial>
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://rc_description/meshes/rabbit/base_link.stl" />
                    </geometry>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://rc_description/meshes/rabbit/base_link.stl" />
                    </geometry>
                </collision>
        </link>

        <joint name="dummy_joint" type="fixed">
            <parent link="dummy"/>
            <child link="base_link"/>
        </joint>

            <xacro:mecanum_wheel prefix="left_front" connected_to="base_link"
                                wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                                wheel_z_offset="${wheel_offset_z}"
                                reflect="1" roller_type="${roller_type}"
                                max_effort="5" max_velocity="50"/>
            <xacro:mecanum_wheel prefix="right_front" connected_to="base_link"
                                wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                                wheel_z_offset="${wheel_offset_z}"
                                reflect="-1" roller_type="${roller_type}"
                                max_effort="5" max_velocity="50"/>
            <xacro:mecanum_wheel prefix="left_back" connected_to="base_link"
                                wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                                wheel_z_offset="${wheel_offset_z}"
                                reflect="-1" roller_type="${roller_type}"
                                max_effort="5" max_velocity="50"/>
            <xacro:mecanum_wheel prefix="right_back" connected_to="base_link"
                                wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                                wheel_z_offset="${wheel_offset_z}"
                                reflect="1" roller_type="${roller_type}"
                                max_effort="5" max_velocity="50"/>
            <xacro:wheel_transmission prefix="left_front" mechanical_reduction="19.2032"/>
            <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-19.2032"/>
            <xacro:wheel_transmission prefix="left_back" mechanical_reduction="19.2032"/>
            <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-19.2032"/>

    </xacro:macro>
</robot>