<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">
    <xacro:include filename="$(find rc_description)/urdf/common/swerve_drive.urdf.xacro"/>
    <xacro:include filename="$(find rc_description)/urdf/common/inertia_utils.urdf.xacro"/>
    <xacro:property name="wheel_track" value="0.3"/>
    <xacro:property name="wheel_base" value="0.3"/>
    <xacro:property name="wheel_offset_z" value="0.054"/>

    <xacro:macro name="chassis" params="roller_type">
        <link name="base_link">
            <xacro:cylinder_inertial_matrix m="3.0" r="0.358" h="0.05"/>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 ${-pi/2.0}"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rc_description/meshes/rabbit/base.stl" scale="1.0 1.0 1.0"/>
                </geometry>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="0.18" length="0.05"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            </collision>
        </link>


        <xacro:swerve_drive prefix="left_front" connected_to="base_link"
                            x_offset="${wheel_track/2}" y_offset="${wheel_base/2}"
                            z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="right_front" connected_to="base_link"
                            x_offset="${wheel_track/2}" y_offset="${-wheel_base/2}"
                            z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="left_back" connected_to="base_link"
                            x_offset="${-wheel_track/2}" y_offset="${wheel_base/2}"
                            z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="right_back" connected_to="base_link"
                            x_offset="${-wheel_track/2}" y_offset="${-wheel_base/2}"
                            z_offset="${wheel_offset_z}"/>

        <xacro:swerve_transmission prefix="left_front" wheel_reduction="-19.2032" pivot_offset="-0.79776"/>
        <xacro:swerve_transmission prefix="right_front" wheel_reduction="-19.2032" pivot_offset="4.68688"/>
        <xacro:swerve_transmission prefix="left_back" wheel_reduction="-19.2032" pivot_offset="0.741"/>
        <xacro:swerve_transmission prefix="right_back" wheel_reduction="-19.2032" pivot_offset="-0.7479"/>

    </xacro:macro>


</robot>